name: Triggers
on:
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/6 * * * *"
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Jeff